#!/bin/sh

project_ctags() {
  PROJECT_ROOT="$(while [ ! -f '.editorconfig' ] && [ '/' != "${PWD}" ]; do cd .. ;done; [ / != "${PWD}"  ] && echo "${PWD}" || echo .)"

  for FILE in "$@"; do
    if [ ! -f "${FILE}" ]; then
      exit 0;
    fi

    EXT="$(echo "${FILE}" | awk -F . '{print $NF}')"

    case ${EXT} in
      php)
        TAG="${PROJECT_ROOT}/php.tags"
        STATUS=$?
        ;;

      js|mjs)
        TAG="${PROJECT_ROOT}/js.tags"
        STATUS=$?
        ;;

      *)
        # no-op
        STATUS=0
        ;;
    esac

    if [ ${STATUS} -ne 0 ]; then
      return ${STATUS}
    else
      ctags -a -f "${TAG}" "${FILE}"
    fi
  done
}

project_ctags ${@}
