#!/bin/sh

project_ctags() {
  PROJECT_ROOT="$(while [ ! -f '.editorconfig' ] && [ '/' != "${PWD}" ]; do cd .. ;done; [ / != "${PWD}"  ] && echo "${PWD}" || echo .)"

  for FILE in "$@"; do
    F="$(echo "${FILE}" | awk -F . '{print $NF}')"
    if [ ! -f "${FILE}" ]; then
      exit 0;
    fi

    case ${F} in
      php)
        TAG="${PROJECT_ROOT}/php.tags"
        ctags -a --fields=+aimlS --PHP-kinds=+cdfint-av -f "${TAG}" "${FILE}"
        STATUS=$?
        ;;

      js|mjs)
        TAG="${PROJECT_ROOT}/js.tags"
        ctags -a -f "${TAG}" "${FILE}"
        STATUS=$?
        ;;

      *)
        # no-op
        STATUS=0
        ;;
    esac

    if [ ${STATUS} -ne 0 ]; then
      exit ${STATUS}
    fi
  done
}

project_ctags ${@}
