#!/bin/sh
. "${HOME}/dotfiles/helpers/project-ctags"

if [ "$(git rev-parse --verify HEAD > /dev/null 2>&1)" = 0 ]; then
	AGAINST=$(git hash-object -t tree /dev/null) # hash of empty tree
else
	AGAINST='HEAD'
fi

FILES="$(git diff-index --cached --name-only ${AGAINST})"

project_ctags ${FILES} >/dev/null 2>&1 &
