#!/bin/sh
. "${HOME}/dotfiles/helpers/project-ctags"

if [ "$(git rev-parse --verify HEAD > /dev/null 2>&1)" = 0 ]; then
	AGAINST='4b825dc642cb6eb9a060e54bf8d69288fbee4904' # hash of empty repo
else
	AGAINST='HEAD'
fi

FILES="$(git diff-index --cached --name-only ${AGAINST})"

project_ctags ${FILES} >/dev/null 2>&1 &
