#!/bin/sh
# vim:ft=sh
# Adapted from PHP via
# @link http://webadvent.org/2008/dont-commit-that-error-by-travis-swicegood.html

if [ "$(git rev-parse --verify HEAD > /dev/null 2>&1)" = 0 ]; then
	AGAINST='4b825dc642cb6eb9a060e54bf8d69288fbee4904' # hash of empty repo
else
	AGAINST='HEAD'
fi

FILES="$(git diff-index --cached --name-only ${AGAINST})"

for FILE in ${FILES}; do
	F="$(echo "${FILE}" | awk -F . '{print $NF}')"
    if [ ! -f "${FILE}" ]; then
        break;
    fi

	case ${F} in
		php)
            ERROR="$(php -l "${FILE}")"
            STATUS=$?
		;;

        js)
            ERROR="$(node --check "${FILE}")"
            STATUS=$?
        ;;

		*)
			# no-op
			ERROR=''
			STATUS=0
		;;
	esac

	if [ ${STATUS} -ne 0 ]; then
		echo "${ERROR}" >&2
		exit ${STATUS}
	fi
done
