#!/usr/bin/env sh
branches='develop|master|main|stage|nonono'
current_branch=$(git symbolic-ref --short HEAD 2>/dev/null)

if echo "$current_branch" | grep -qE "^(${branches})$"; then
    echo "Error: Cannot push to protected branch: $current_branch" >&2
    exit 1
fi
