#!/bin/sh
# vim:ft=sh
# Adapted from PHP via
# @link http://webadvent.org/2008/dont-commit-that-error-by-travis-swicegood.html

# shellcheck source=/home/darc/dotfiles/helpers/project-ctags
. "${HOME}/dotfiles/helpers/project-ctags"

if [ "$(git rev-parse --verify HEAD > /dev/null 2>&1)" = 0 ]; then
	AGAINST=$(git hash-object -t tree /dev/null) # hash of empty tree
else
	AGAINST='HEAD'
fi

FILES="$(git diff-index --cached --name-only ${AGAINST})"

for FILE in ${FILES}; do
	F="$(echo "${FILE}" | awk -F . '{print $NF}')"
	if [ ! -f "${FILE}" ]; then
		break;
	fi

	case ${F} in
		cs)
			ERROR="$(mscs --check "${FILE}")"
			STATUS=$?
			;;

		php)
			ERROR="$(php -l "${FILE}")"
			STATUS=$?
			;;

		py)
			ERROR="$(python -m py_compile "${FILE}")"
			STATUS=$?
			;;

		js|mjs)
			ERROR="$(node --check "${FILE}")"
			STATUS=$?
			;;

		ts)
			ERROR="$(tsc --target es2019 --noEmit "${FILE}")"
			STATUS=$?
			;;

		lua)
			ERROR="$(luac -p "${FILE}")"
			STATUS=$?
			;;

		*)
			# no-op
			ERROR=''
			STATUS=0
			;;
	esac

	if [ ${STATUS} -ne 0 ]; then
		echo "${ERROR}" >&2
		exit ${STATUS}
	fi
done

# shellcheck disable=SC2086
project_ctags ${FILES} >/dev/null 2>&1 &
